# Generated by Django 5.0.6 on 2024-05-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('foto', models.ImageField(null=True, upload_to='fotos/', verbose_name='Foto')),
                ('clase', models.TextField(null=True, verbose_name='Clase')),
            ],
        ),
    ]
